export const Gents= {
    title:"GentsFashion",
    image1:"assets/men/1.jpg",
    image2:"assets/men/2.jpg",
    image3:"assets/men/3.jpg",
    image4:"assets/men/4.jpg",
    image5:"assets/men/5.jpg",
    image6:"assets/men/6.jpg",
    price1:"559 INR",
    price2:"759 INR",
    price3:"479 INR",
    price4:"519 INR",
    price5:"670 INR",
    price6:"899 INR",
}
 export const Women={
    title:"WomensFasion",
    image1:"assets/women/1.jpg",
    image2:"assets/women/2.jpg",
    image3:"assets/women/3.jpg",
    image4:"assets/women/4.jpg",
    image5:"assets/women/5.jpg",
    image6:"assets/women/6.jpg",

    price2:"759 INR",
    price3:"479 INR",
    price4:"519 INR",
    price5:"670 INR",
    price6:"899 INR",
}
